In [1]:
e= np.arange(1,11)

NameError: name 'np' is not defined

In [59]:
import numpy as np

In [4]:
e= np.arange(1,11)

In [5]:
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a= np.array([[1,2,3],[10,20,30]])
b= np.array([[5,6,7],[40,50,60]])

In [14]:
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [15]:
b

array([[ 5,  6,  7],
       [40, 50, 60]])

In [16]:
c=np.hstack((a,b))

In [17]:
c

array([[ 1,  2,  3,  5,  6,  7],
       [10, 20, 30, 40, 50, 60]])

In [20]:
d= np.vstack((a,b))

In [21]:
d

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 5,  6,  7],
       [40, 50, 60]])

In [22]:
e= np.arange(1,11)

In [23]:
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
f=np.arange(2,21,2)

In [25]:
f

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
g=np.arange(13,131,13)

In [29]:
g

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [30]:
h=np.linspace(1.0,3.0,num=10)

In [31]:
h

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [34]:
i=np.array([[1,2,3],[4,5,6]])

In [35]:
i

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
i.size

6

In [37]:
i.shape

(2, 3)

In [38]:
i[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
i[0:1]

array([[1, 2, 3]])

In [44]:
i[1:2]

array([[4, 5, 6]])

In [45]:
i[0]

array([1, 2, 3])

In [46]:
i[1]

array([4, 5, 6])

In [47]:
i[:,2]

array([3, 6])

In [74]:
arr = np.random.randint(0,10, size=(3,2))

In [75]:
print(arr)

[[5 9]
 [7 1]
 [5 6]]


In [76]:
i+=2

In [77]:
print(arr.shape)

(3, 2)


In [78]:
i

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [79]:
i.min()

5

In [80]:
arr.reshape(3,2)

array([[5, 9],
       [7, 1],
       [5, 6]])

In [81]:
print("After Reshape")

After Reshape


In [84]:
arr = arr.reshape(9, 1)

ValueError: cannot reshape array of size 6 into shape (9,1)

In [83]:
print(arr)

[[5 9]
 [7 1]
 [5 6]]
